/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '13/12/16 10:18' with Gradle 2.13
 *
 * @author mati, @date 13/12/16 10:18
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
