/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'juansergio' at '12/02/17 11:53' with Gradle 2.14.1
 *
 * @author juansergio, @date 12/02/17 11:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
